namespace: argocd

bases:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.8.6
  #- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.8.7

resources:
- resources/namespace.yaml
  #- apps/argocd.yaml # Edit the file before applying!
  #- apps/kube_prometheus_stack.yaml # Edit the file before applying!

#patchesStrategicMerge:
#- overlays/argocd-cm.yaml
#- overlays/argocd-repo-server-deploy.yaml
