# Multiple notifications bug: https://github.com/argoproj-labs/argocd-notifications/issues/90
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  context: |
    myUsername: "Jane Doe" # ADD HERE YOUR USERNAME
  service.webhook.discord: |
      url: "https://discord.com/api/webhooks/817768528722788385/gdUZzKP0HOkB2xSD_iq6AxlFZZMNRkXQBLCeymMfE1ebnINquB-BkLVg59w6SnzJDhFS" # ADD HERE YOUR URL
    headers:
    - name: Content-Type
      value: application/json
  template.app-sync-succeeded: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "content": ":white_check_mark: - {{.context.myUsername}} synced their application successfully! \n:rocket: -  URL: {{call .repo.FullNameByRepoURL .app.spec.source.repoURL}}",
            "username": "ArgoCD",
            "avatar_url": "https://cncf-branding.netlify.app/img/projects/argo/icon/color/argo-icon-color.png"
          }
