--- # All configs: https://argoproj.github.io/argo-cd/operator-manual/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.discord: "discord-notification"
spec:
  project: default
  source:
    repoURL: https://github.com/AndreaGiardini/GitOps-workshop.git # REPLACE ME!
    targetRevision: HEAD
    path: app_kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
